package:
  name: bodyposition
  version: "0.0.2"

source:
# this is used for build from git hub
  git_rev: 0.0.2
  git_url: https://github.com/mjirik/bodyposition.git

# this is used for pypi 
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  ignore_run_exports:
      - python_abi
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - io3d = io3d:main
    #
    # Would create an entry point called io3d that calls io3d.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python=3.7
    - setuptools
    - numpy
    - scipy
    - imtools
    - scikit-image
    - io3d
    - pandas
    - sed3
    - loguru
    - imma
    - tensorflow=2.1
    - keras
    - h5py
    - SimpleITK


  run:
    - python=3.7
    - numpy
    - scipy
    - scikit-image
    - io3d
    - pandas
    - sed3
    - imma
    - dill
    - loguru
    - tensorflow=2.1
    - h5py
    - SimpleITK

test:
  # Python imports
  imports:
    - bodyposition

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/bodynposition
  license: MIT License
  summary: 'Segmentation of signed distance fields in anatomy using U-net neural networks.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
